melodramatick/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import SignUpView, ProfileView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path("<slug:username>", ProfileView.as_view(), name='profile'),
]

melodramatick/composer/urls.py
from django.urls import path

from . import views

app_name = 'composer'
urlpatterns = [
    path('', views.ComposerListView.as_view(), name='index'),
    path('composer-autocomplete/', views.ComposerAutocomplete.as_view(), name="composer-autocomplete"),
]

melodramatick/listen/urls.py
from django.urls import path

from .views import spotify_playback_view

app_name = 'listen'
urlpatterns = [
    path("play/<work>/", spotify_playback_view, name="playback"),
]

melodramatick/top_list/urls.py
from django.urls import path

from . import views

app_name = 'top_list'
urlpatterns = [
    path('', views.TopListView.as_view(), name='index'),
]

melodramatick/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
import notifications.urls

from .admin import user_admin
from .views import HomePageView


urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('accounts/', include('melodramatick.accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path('adminactions/', include('adminactions.urls')),
    path('user-admin/', user_admin.urls),
    path('composers/', include('melodramatick.composer.urls')),
    path('top-lists/', include('melodramatick.top_list.urls')),
    path('performances/', include('melodramatick.performance.urls')),
    path('', include('melodramatick.listen.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

if settings.DEVELOPMENT_MODE is True:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))


tick_app = settings.INSTALLED_APPS[0]
urlpatterns.append(path('works/', include('{}.urls'.format(tick_app))))

melodramatick/accounts/models.py
__all__ = ["CustomUser"]
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    spotify_player = models.CharField(choices=[("web", "Web player"), ("app", "Desktop app")], default="app", null=True,
                                      max_length=3)

    def __str__(self):
        return self.username

melodramatick/models.py
# flake8: noqa

from melodramatick.accounts.models import *
from melodramatick.composer.models import *
from melodramatick.listen.models import *
from melodramatick.performance.models import *
from melodramatick.top_list.models import *
from melodramatick.work.models import *

melodramatick/accounts/forms.py
from django.contrib.auth.models import Permission
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.contenttypes.models import ContentType

from .models import CustomUser
from melodramatick.performance.models import Performance


class CustomUserCreationForm(UserCreationForm):

    def save(self, commit=True):
        user = super().save(commit)
        content_type = ContentType.objects.get_for_model(Performance)
        change_permission = Permission.objects.get(codename="change_performance", content_type=content_type)
        view_permission = Permission.objects.get(codename="view_performance", content_type=content_type)
        user.user_permissions.add(change_permission)
        user.user_permissions.add(view_permission)
        if commit:
            user.save()
        return user

    class Meta:
        model = CustomUser
        fields = ('username', 'email')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

melodramatick/forms.py
from django import forms


class CsvImportForm(forms.Form):
    csv_file = forms.FileField()


class TxtImportForm(forms.Form):
    txt_file = forms.FileField()

melodramatick/listen/forms.py
from urllib.parse import urlparse

from django import forms

from .models import Album


class AlbumForm(forms.ModelForm):
    def save(self, commit):
        album_type, id = filter(None, urlparse(self.instance.url).path.split('/'))
        self.instance.id = id
        self.instance.uri = "spotify:{}:{}".format(album_type, id)
        return super().save(commit)

    class Meta:
        model = Album
        fields = "__all__"

melodramatick/accounts/views.py
from operator import itemgetter

from django.db.models import Count, Max, Sum, Q
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie
from django.views.generic import DetailView
from django.views.generic.edit import CreateView

from .forms import CustomUserCreationForm
from .models import CustomUser
from melodramatick.composer.models import Composer
from melodramatick.listen.models import Listen
from melodramatick.listen.plots import plot_listens_per_week
from melodramatick.performance.models import Company, Performance, Venue
from melodramatick.performance.plots import plot_perfs_per_year
from melodramatick.utils.annotation import user_listens_per_era
from melodramatick.work.models import Work


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'


@method_decorator([vary_on_cookie, cache_page(60 * 1)], name='dispatch')
class ProfileView(DetailView):
    model = CustomUser
    slug_field = "username"
    slug_url_kwarg = "username"
    template_name = 'accounts/profile.html'

    def _set_awards_tab_context_data(self, context):
        context["progress"] = sorted(
            self.user.progress.filter(count__gt=0).filter(list__site=self.request.site),
            key=lambda x: x.ticks_to_next_award)
        context["awards"] = sorted(
            self.user.award.filter(list__site=self.request.site),
            key=lambda x: (x.level.rank, -x.list.length))

    def _set_performances_tab_context_data(self, context):
        context["performances"] = Performance.objects.filter(user=self.user).order_by('-date')
        context["most_watched"] = Work.objects.annotate(
            tally=Count("performance", filter=Q(
                performance__user=self.user,
                performance__site=self.request.site))
            ).order_by("-tally").first()
        context["most_visited"] = Venue.objects.annotate(
            tally=Count("performance", filter=Q(
                performance__user=self.user,
                performance__streamed=False,
                performance__site=self.request.site))
            ).order_by("-tally").first()
        context["most_watched_company"] = Company.objects.annotate(
            tally=Count("performance", filter=Q(
                performance__user=self.user,
                performance__site=self.request.site))
            ).order_by("-tally").first()
        context["most_watched_composer"] = Composer.objects.annotate(
            tally=Count("work__performance", filter=Q(
                work__performance__user=self.user,
                work__performance__site=self.request.site))
            ).order_by("-tally").first()
        context["perfs_per_year"] = plot_perfs_per_year(context["performances"], figsize=(6, 6))

    def _set_listens_tab_context_data(self, context):
        context["listens"] = Listen.objects.filter(user=self.user)
        max_tally = context["listens"].aggregate(Max("tally"))["tally__max"]
        context["most_listened"] = context["listens"].filter(tally=max_tally).first()
        context["most_listened_composer"] = Composer.objects.annotate(
            tally=Sum("work__listen__tally", filter=Q(
                work__listen__user=self.user,
                work__listen__site=self.request.site))
            ).order_by("-tally").first()
        try:
            context["most_listened_era"] = max(
                user_listens_per_era(Work.objects.all(), self.user),
                key=itemgetter(1)
            )
        except ValueError:
            pass
        context["listens_per_week"] = plot_listens_per_week(context["listens"], figsize=(6, 6))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.user = self.get_object()
        self._set_awards_tab_context_data(context)
        self._set_performances_tab_context_data(context)
        self._set_listens_tab_context_data(context)
        return context

melodramatick/composer/views.py
from dal import autocomplete
from django.db.models import Count, F, FloatField, IntegerField, Case, When, Q
from django.db.models.functions import Cast
from django_filters.views import FilterView
from django_tables2 import SingleTableMixin

from .filters import ComposerFilter
from .models import Composer
from .tables import ComposerTable


class ComposerAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Composer.objects.none()
        qs = Composer.objects.all()
        if self.q:
            qs = qs.filter(surname__istartswith=self.q)
        return qs


class ComposerListView(SingleTableMixin, FilterView):
    model = Composer
    table_class = ComposerTable
    template_name = 'composer/index.html'
    filterset_class = ComposerFilter

    def get_table_data(self):
        table_data = super().get_table_data()
        return (
            table_data
            .annotate(
                total_works=Count("work", filter=Q(work__site=self.request.site), distinct=True),
                total_top_lists=Count("work__list_item", filter=Q(work__site=self.request.site), distinct=True)
            ).annotate(
                top_lists_to_works=Cast(F("total_top_lists"), IntegerField()) / Cast(F("total_works"), FloatField()),
            )
            # ).annotate(
            #     impact=Case(
            #         When(total_operas__lt=F("top_lists_to_operas"), then=F("total_operas")),
            #         default=F("top_lists_to_operas"),
            #         output_field=FloatField()
            #     )
            # )
        )

    def get_table_kwargs(self):
        return {
            'order_by': ('total_top_lists',)
        }

melodramatick/listen/views.py
from urllib.parse import urlparse

from django.conf import settings
from django.shortcuts import redirect

from .models import Listen
from melodramatick.work.models import Work


def spotify_playback_view(request, **kwargs):
    work_id = kwargs.get('work')
    work = Work.objects.get(id=work_id)
    listen, _ = Listen.objects.get_or_create(user=request.user, work=work, site=request.site)
    listen.tally += 1
    listen.save()

    referer_url = request.META.get('HTTP_REFERER')
    # Avoid feedback loop with login page redirects
    if referer_url and not urlparse(referer_url).path == settings.LOGIN_URL:
        return redirect(referer_url)
    else:
        return redirect('home')

melodramatick/performance/views.py
from django.shortcuts import redirect

from melodramatick.work.models import Work
from .models import Performance


def tick_view(request, **kwargs):
    work_id = kwargs.get('work')
    work = Work.objects.get(id=work_id)
    performances = Performance.objects.filter(user=request.user, work=work)
    if not performances:
        performance = Performance.objects.create(user=request.user, site=request.site)
        performance.work.add(work)
    else:
        for p in performances:
            p.delete()

    return redirect(request.META.get('HTTP_REFERER'))

melodramatick/top_list/views.py
from django.db.models import Count, Max
from django_tables2 import SingleTableView

from .models import List
from .tables import TopListTable


class TopListView(SingleTableView):
    model = List
    table_class = TopListTable
    template_name = 'top_list/index.html'

    def get_table_data(self):
        table_data = super().get_table_data()
        return table_data.annotate(
            max_position=Max("listitem__position"),
            list_work_count=Count("items")
        )

melodramatick/views.py
from django.views.generic.base import TemplateView

from melodramatick.utils.randomisers import quote_of_the_day, work_of_the_day


class HomePageView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["qod"] = quote_of_the_day()
        context["wod"] = work_of_the_day(self.request.user)
        return context

melodramatick/work/views.py
import random

from django.db.models import Count, Q, Sum
from django.db.models.functions import Coalesce
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie
from django.views.generic import DetailView, ListView
from django_filters.views import FilterView
from django_tables2 import SingleTableMixin

from . import plots
from .models import Work
from melodramatick.listen.models import Listen
from melodramatick.utils.rendering import render_tickbox


class WorkTableView(SingleTableMixin, FilterView):
    model = Work
    # table_class = OperaTable
    template_name = 'work/index.html'
    # filterset_class = OperaFilter

    def render_to_response(self, context, **kwargs):
        """
        Add a randomly chosen album uri from the filtered queryset to context
        """
        qs_with_links = self.object_list.exclude(album__id__isnull=True)
        if qs_with_links:
            random_pick = qs_with_links[random.randint(0, len(qs_with_links)-1)]
            try:
                album_id = random_pick.uri
            except AttributeError:
                album_id = random_pick.random_uri
            context['random_uri'] = album_id
            context['work_id'] = random_pick.id
        return super().render_to_response(context, **kwargs)

    def get_table_data(self):
        table_data = super().get_table_data()
        return table_data.annotate(
            user_listens=Sum("listen__tally", filter=Q(listen__user=self.request.user), distinct=True),
            user_performances=Count("performance", filter=Q(performance__user=self.request.user), distinct=True),
            total_lists=Count("list", distinct=True)
        )

    def get_table_kwargs(self):
        """
        Remove column from table if it is being filtered over.
        Handle ordering when particular filters are selected.
        """
        excluded = set()
        order_by = ('total_lists', 'year')
        excluded.update(('position', 'duration', 'uri'))
        for k, v in self.request.GET.items():
            if v:
                excluded.add(k)
                if k == 'top_list':
                    excluded.discard('position')
                    excluded.add('total_lists')
                    order_by = ('position',)
                elif 'duration_range' in k:
                    excluded.discard('duration')
                    excluded.discard('uri')
                    excluded.add("random_uri")
                    order_by = ('duration',)
        return {
            'exclude': excluded,
            'order_by': order_by
        }


@method_decorator([vary_on_cookie, cache_page(60 * 60)], name='dispatch')
class WorkGraphsView(ListView):
    template_name = 'work/work_graphs.html'
    model = Work

    def get_context_data(self, **kwargs):
        qs = self.object_list.annotate(
                user_listens=Coalesce(Sum('listen__tally', filter=Q(listen__user=self.request.user)), 0),
                user_perfs=Count('performance', filter=Q(performance__user=self.request.user) & Q(performance__streamed=False))
            )
        top = plots.plot_works_by_decade(qs, figsize=(12, 6))
        middle_left = plots.plot_works_per_composer(qs, figsize=(4, 6))
        middle_centre = plots.plot_perfs_per_composer(qs, figsize=(4, 6))
        middle_right = plots.plot_listens_per_composer(qs, figsize=(4, 6))
        bottom_left = plots.plot_works_per_era(qs, figsize=(3, 6))
        bottom_centre = plots.plot_perfs_per_era(qs, figsize=(3, 6))
        bottom_right = plots.plot_listens_per_era(qs, figsize=(3, 6))
        duration_hist = plots.plot_duration_hist(qs, figsize=(12, 6))
        top_lists_bar = plots.plot_top_lists_by_decade(qs, figsize=(12, 6))
        context = {
            'top': top,
            'middle_left': middle_left,
            'middle_centre': middle_centre,
            'middle_right': middle_right,
            'bottom_left': bottom_left,
            'bottom_centre': bottom_centre,
            'bottom_right': bottom_right,
            'duration_hist': duration_hist,
            'top_lists_bar': top_lists_bar,
            'work_count': self.object_list.count(),
            'user_performance_count': qs.aggregate(Sum('user_perfs'))['user_perfs__sum'],
            'user_listen_count': qs.aggregate(Sum('user_listens'))['user_listens__sum'],
        }
        return context


class WorkDetailView(DetailView):
    model = Work

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["ticked"], context["tickbox"] = render_tickbox(self.request.user, self.object, scale=2)
        try:
            context["listen_count"] = self.object.listen.get(user=self.request.user.id).tally
        except Listen.DoesNotExist:
            context["listen_count"] = 0
        return context

melodramatick/templates/base.html
{% load static %}
{% load settings %}
{% load notifications_tags %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}{% endblock %} | {% settings_value "SITE" %}</title>
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}"/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ttskch/select2-bootstrap4-theme@1.5.2/dist/select2-bootstrap4.min.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Source+Serif+Pro:wght@300&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap4.min.css">
	<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap4.min.js"></script>
  <script>
    $(document).ready(function() {
      get_web_app_url = (a, typ, id) => `https://open.spotify.com/${typ}/${id}`
      var is_web_player = "{{ request.user.spotify_player }}" === "web";
      $(document).on('click', '.spotify_play', function() {
        let url = $(this).find("img").attr("uri");
        if( is_web_player ){
          url = get_web_app_url(...url.split(":"));
        }
        window.open(url, "_blank");
      });
      $(document).on('click', '.spotify_link', function() {
        let url = $(this).attr("href");
        if( is_web_player ){
          url = get_web_app_url(...url.split(":"));
        }
        window.open(url, "_blank");
        return false;
      });
      $('[data-toggle="tooltip"]').tooltip();
      new DataTable('#listeningHistoryTable', {
        order: [[0, 'desc']]
      });
      new DataTable('#performanceHistoryTable', {
        order: [[0, 'desc']]
      });
    });
  </script>
  <style>
    th.asc a {
      padding-right: 16px;
      background-repeat: no-repeat;
      background-position: right center;
      background-image: url("{% static 'images/sort_asc.png' %}");
    }

    th.desc a {
      padding-right: 16px;
      background-repeat: no-repeat;
      background-position: right center;
      background-image: url("{% static 'images/sort_desc.png' %}");
    }

    .select2-selection--single {
      padding-bottom: 24px;
    }

    .select2-selection__arrow {
      visibility: hidden;
    }

    .select2-results__options {
      max-height: 250px;
      overflow-y: auto;
    }
  </style>
  {% block head %}{% endblock %}
</head>
<body>
  {% block nav %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">
        <img src="{% static 'images/banner.png' %}" alt="" class="img-responsive" style="height: 60px;">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% block nav-home%}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>
          {% endblock %}
          {% if user.is_authenticated %}
            {% block nav-table %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'work:index' %}">Table</a>
            </li>
            {% endblock %}
            {% block nav-top-list %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'top_list:index' %}">Top Lists</a>
            </li>
            {% endblock%}
            {% block nav-composers %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'composer:index' %}">Composers</a>
            </li>
            {% endblock%}
            {% block nav-graphs %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'work:graphs' %}">Graphs</a>
            </li>
            {% endblock %}
          {% endif %}
          {% block more-links %}{% endblock %}
          {% comment %} <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li> {% endcomment %}
          {% comment %} <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li> {% endcomment %}
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
          {% block nav-notifications %}
            {% notifications_unread as unread_count %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'notifications:unread' %}">
                <i class="fa-solid fa-inbox">{% if unread_count %}{% live_notify_badge badge_class="live_notify_badge badge badge-pill badge-danger" %}{% endif %}</i>
              </a>
            </li>
          {% endblock %}
          {% block nav-profile %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'profile' user.username %}">Profile</a>
            </li>
          {% endblock %}
          {% block nav-admin %}
            <li class="nav-item">
              {% if user.is_superuser %}
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
              {% else %}
              <a class="nav-link" href="{% url 'user-admin:index' %}">Admin</a>
              {% endif %}
            </li>
            {% endblock %}
            {% block nav-logout %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
            </li>
            {% endblock %}
          {% else %}
            {% block nav-login %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Log In</a>
            </li>
            {% endblock %}
            {% block nav-signup %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
            </li>
            {% endblock %}
          {% endif %}
        </ul>
        {% comment %} <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> {% endcomment %}
      </div>
    </nav>
  {% endblock %}
  <main>
    <div class="container-fluid pt-2">
      {% if messages %}
        {% for message in messages %}
          <h4 style="color:red; font-family: 'Source Serif Pro', serif;" class="messages"><strong>{{ message }}</strong></h4>
        {% endfor %}
      {% endif %}
      {% block content %}
      {% endblock %}
    </div>
  </main>
  <script src="{% static 'notifications/notify.js' %}" type="text/javascript"></script>
  {% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %}
  <footer class="border-top bd-footer bg-light">
    <div class="container-fluid py-3">
      <p class="text-center">{% settings_value "SITE" %} is a Melodramatick site.</p>
    </div>
  </footer>
</body>
</html>

melodramatick/templates/home.html
{% extends 'base.html' %}
{% load settings %}
{% load static %}
{% load notifications_tags %}
{% load humanize %}

{% block title %}Home{% endblock %}

{% block nav-home %}
  <li class="nav-item active">
    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
  </li>
{% endblock %}

{% block content %}
  <div class="row" style="background-color: {% settings_value 'BACKGROUND_COLOUR' %}; padding: 16px;">
    <img class="mx-auto d-block img-fluid" src="{% static 'images/banner.png' %}" alt="">
  </div>
  <div class="row" style="margin: 50px;">
    {% if user.is_authenticated %}
      <div>
        <h3>Hi {{ user.username }}!</h3>
        {% notifications_unread as unread_count %}
        {% if unread_count %}
        <p>You have <strong>{{ unread_count }}</strong> unread notifications.</p>
        {% endif %}
      </div>
    {% else %}
      <ul class="list-unstyled">
        <li><p>You are not logged in</p></li>
        <li>
          <a href="{% url 'login' %}">Log In</a> |
          <a href="{% url 'signup' %}">Sign Up</a>
        </li>
      </ul>
    {% endif %}
  </div>
  <div class="row" style="margin: 50px;">
    <div class="card-deck">
      {% if wod %}
        <div class="card">
          <div class="card-header">
            Featured Work
          </div>
          <a class="spotify_link" href="{{ wod.random_album.uri }}:play">
            <img class="card-img-top" src="{{ wod.random_album.image }}" alt="Album cover" style="max-width: 30em;">
          </a>
          <div class="card-body">
            <h3 class="card-title">{{ wod.title }} by {{ wod.composer.full_name }}</h3>
            {% if wod.composer.anniversary %}
            <h5 class="cart-subtitle mb-2 text-muted">Happy {{ wod.composer.anniversary|ordinal }} Birthday!</h5>
            {% endif %}
            <p class="card-text">
              {{ wod.year }}
              {% if wod.sub_genre %}{{ wod.sub_genre }}{% else %}{{ wod.type|capfirst }}{% endif %}
              {% if wod.instrument %} for {{ wod.instrument_verbose }}{% endif %}
              {% if wod.language %} in {{ wod.language_verbose }}{% endif %}
              {% if wod.notes %}<br>{{ wod.notes }}{% endif %}
            </p>
            <a class="spotify_play" href="/play/{{ wod.id }}/" title="Play on Spotify">
              <img uri="{{ wod.random_album.uri }}:play" src="/static/images/Spotify-Play-Button.png" width="38px;">
            </a>
            {% if wod.listen_count %}({{ wod.listen_count }} listen{{ wod.listen_count|pluralize:",s" }}){% endif %}
            <a class="btn btn-primary float-right" href="{% url 'work:work-detail' wod.id %}">More details</a>
          </div>
        </div>
      {% endif %}
      {% if qod %}
        <div class="card">
          <div class="card-header">
            Quote of the Day
          </div>
          <div class="card-body">
            <blockquote class="blockquote mb-0">
              <p>{{ qod }}</p>
              <footer class="blockquote-footer">{{ qod.composer.full_name }}</footer>
            </blockquote>
          </div>
        </div>
      {% endif %}
    </div>
  </div>
  <div class="row" style="margin: 50px;">
    <a class="twitter-timeline" data-lang="en" data-height="500" data-width="750" href="https://twitter.com/flittingpie/lists/1673686262048235526?ref_src=twsrc%5Etfw"></a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  </div>
{% endblock %}