melodramatick/performance/urls.py
from django.urls import path

from .views import tick_view

app_name = 'performance'
urlpatterns = [
    path("tick/<work>/", tick_view, name="tick"),
]

melodramatick/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
import notifications.urls

from .admin import user_admin
from .views import HomePageView


urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('accounts/', include('melodramatick.accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path('adminactions/', include('adminactions.urls')),
    path('user-admin/', user_admin.urls),
    path('composers/', include('melodramatick.composer.urls')),
    path('top-lists/', include('melodramatick.top_list.urls')),
    path('performances/', include('melodramatick.performance.urls')),
    path('', include('melodramatick.listen.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
]

if settings.DEVELOPMENT_MODE is True:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))


tick_app = settings.INSTALLED_APPS[0]
urlpatterns.append(path('works/', include('{}.urls'.format(tick_app))))

melodramatick/work/models.py
__all__ = ["AKA", "Genre", "SubGenre", "Work"]
import datetime
import random

from django.conf import settings
from django.contrib.sites.models import Site
from django.core.cache import cache
from django.db import models
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from polymorphic.models import PolymorphicModel

from melodramatick.composer.models import Composer
from melodramatick.utils.managers import CurrentSitePolymorphicManager
from melodramatick.utils.models import AbstractSingleSiteModel


class Genre(AbstractSingleSiteModel):
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class SubGenre(AbstractSingleSiteModel):
    name = models.CharField(max_length=50)
    genre = models.ForeignKey(Genre, on_delete=models.PROTECT, null=True, blank=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Work(PolymorphicModel):
    composer = models.ForeignKey(Composer, on_delete=models.PROTECT)
    title = models.CharField(max_length=100, db_index=True)
    year = models.IntegerField(choices=settings.YEAR_CHOICES, default=datetime.datetime.now().year)
    notes = models.TextField(null=True, blank=True)
    sub_genre = models.ForeignKey(SubGenre, on_delete=models.PROTECT, null=True, blank=True)
    site = models.ForeignKey(Site, on_delete=models.PROTECT)
    objects = CurrentSitePolymorphicManager()

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['composer', 'title'], name='unique_work')
        ]
        ordering = ['title']

    def __str__(self):
        if len(Work.objects.filter(title=self.title)) > 1 or settings.VERBOSE_TITLE:
            return "{} ({})".format(self.title, self.composer.surname)
        return self.title

    @property
    def random_uri(self):
        albums = self.album.all()
        if albums:
            uris = [a.uri for a in albums]
            if len(uris) > 1:
                return uris[random.randint(0, len(uris)-1)]
            return uris[0]
        else:
            return None

    @property
    def era(self):
        for years, era in settings.ERAS_MAP:
            start, end = map(int, years.split("-"))
            if self.year in range(start, end + 1):
                return era

    @property
    def top_lists(self):
        return len(self.list_item.all())

    @property
    def type(self):
        return self.polymorphic_ctype.model


@receiver([post_save, post_delete], sender=Work, dispatch_uid="update_work")
def clear_cache_work(*args, **kwargs):
    cache.clear()


class AKA(models.Model):
    work = models.ForeignKey(Work, on_delete=models.CASCADE, related_name="aka")
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

melodramatick/work/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import StrictButton
from crispy_forms.layout import Div, Field, HTML, Layout, Row
from django import forms
from django_filters.fields import RangeField


class WorkFilterFormHelper(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = 'get'
        self.helper.form_show_labels = False
        self.helper.form_class = 'form-horizontal'
        layout_fields = []
        for field_name, field in self.fields.items():
            if isinstance(field, RangeField):
                slider_field = Field(field_name, template="forms/fields/range-slider.html")
            else:
                layout_fields.append(Field(field_name, css_class="custom-select custom-select-sm"))
        dropdowns = Div(Row(*layout_fields), css_class="col-md-8")
        self.helper.layout = Layout(Row(dropdowns,
                                    Div(slider_field, css_class="col-md-4")),
                                    Row(StrictButton("Filter", name='submit', type='submit', css_class='btn btn-primary'),
                                        HTML('<a class="btn btn-secondary" href={% url "work:index" %}>Reset</a>')))

melodramatick/work/views.py
import random

from django.db.models import Count, Q, Sum
from django.db.models.functions import Coalesce
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie
from django.views.generic import DetailView, ListView
from django_filters.views import FilterView
from django_tables2 import SingleTableMixin

from . import plots
from .models import Work
from melodramatick.listen.models import Listen
from melodramatick.utils.rendering import render_tickbox


class WorkTableView(SingleTableMixin, FilterView):
    model = Work
    # table_class = OperaTable
    template_name = 'work/index.html'
    # filterset_class = OperaFilter

    def render_to_response(self, context, **kwargs):
        """
        Add a randomly chosen album uri from the filtered queryset to context
        """
        qs_with_links = self.object_list.exclude(album__id__isnull=True)
        if qs_with_links:
            random_pick = qs_with_links[random.randint(0, len(qs_with_links)-1)]
            try:
                album_id = random_pick.uri
            except AttributeError:
                album_id = random_pick.random_uri
            context['random_uri'] = album_id
            context['work_id'] = random_pick.id
        return super().render_to_response(context, **kwargs)

    def get_table_data(self):
        table_data = super().get_table_data()
        return table_data.annotate(
            user_listens=Sum("listen__tally", filter=Q(listen__user=self.request.user), distinct=True),
            user_performances=Count("performance", filter=Q(performance__user=self.request.user), distinct=True),
            total_lists=Count("list", distinct=True)
        )

    def get_table_kwargs(self):
        """
        Remove column from table if it is being filtered over.
        Handle ordering when particular filters are selected.
        """
        excluded = set()
        order_by = ('total_lists', 'year')
        excluded.update(('position', 'duration', 'uri'))
        for k, v in self.request.GET.items():
            if v:
                excluded.add(k)
                if k == 'top_list':
                    excluded.discard('position')
                    excluded.add('total_lists')
                    order_by = ('position',)
                elif 'duration_range' in k:
                    excluded.discard('duration')
                    excluded.discard('uri')
                    excluded.add("random_uri")
                    order_by = ('duration',)
        return {
            'exclude': excluded,
            'order_by': order_by
        }


@method_decorator([vary_on_cookie, cache_page(60 * 60)], name='dispatch')
class WorkGraphsView(ListView):
    template_name = 'work/work_graphs.html'
    model = Work

    def get_context_data(self, **kwargs):
        qs = self.object_list.annotate(
                user_listens=Coalesce(Sum('listen__tally', filter=Q(listen__user=self.request.user)), 0),
                user_perfs=Count('performance', filter=Q(performance__user=self.request.user) & Q(performance__streamed=False))
            )
        top = plots.plot_works_by_decade(qs, figsize=(12, 6))
        middle_left = plots.plot_works_per_composer(qs, figsize=(4, 6))
        middle_centre = plots.plot_perfs_per_composer(qs, figsize=(4, 6))
        middle_right = plots.plot_listens_per_composer(qs, figsize=(4, 6))
        bottom_left = plots.plot_works_per_era(qs, figsize=(3, 6))
        bottom_centre = plots.plot_perfs_per_era(qs, figsize=(3, 6))
        bottom_right = plots.plot_listens_per_era(qs, figsize=(3, 6))
        duration_hist = plots.plot_duration_hist(qs, figsize=(12, 6))
        top_lists_bar = plots.plot_top_lists_by_decade(qs, figsize=(12, 6))
        context = {
            'top': top,
            'middle_left': middle_left,
            'middle_centre': middle_centre,
            'middle_right': middle_right,
            'bottom_left': bottom_left,
            'bottom_centre': bottom_centre,
            'bottom_right': bottom_right,
            'duration_hist': duration_hist,
            'top_lists_bar': top_lists_bar,
            'work_count': self.object_list.count(),
            'user_performance_count': qs.aggregate(Sum('user_perfs'))['user_perfs__sum'],
            'user_listen_count': qs.aggregate(Sum('user_listens'))['user_listens__sum'],
        }
        return context


class WorkDetailView(DetailView):
    model = Work

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["ticked"], context["tickbox"] = render_tickbox(self.request.user, self.object, scale=2)
        try:
            context["listen_count"] = self.object.listen.get(user=self.request.user.id).tally
        except Listen.DoesNotExist:
            context["listen_count"] = 0
        return context

melodramatick/work/templates/work/index.html
{% extends 'base.html' %}

{% load settings %}
{% load static %}
{% load crispy_forms_tags %}
{% load render_table from django_tables2 %}
{% load bootstrap4 %}

{% block title %}Table of works{% endblock %}
{% block head %}
  <link rel="stylesheet" href="{% static 'css/custom_slider.css' %}">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
    $(document).ready(function() {
      $(document).on('click', '.expand_all', function() {
        $("tr[id^=ticked]").next().find('p').slideDown();
      });
      $(document).on('click', '.collapse_all', function() {
        $("p[class=expanded]").slideUp();
      });
      $("td[id=hiddencell]").find("p").hide();
      $("table").click(function(event) {
        var $target = $(event.target);
        if ( $target.closest("td").attr("colspan") > 1 ) {
          $target.closest("td").children("p").slideUp();
        } else {
          $target.closest("tr[id^=ticked]").next().find("p").slideToggle();
        }
      });
      {% comment %} $("table a").click(function(event) {
        event.stopImmediatePropagation();
      }); {% endcomment %}
    });
  </script>

  <style>
    table {
      border-collapse: collapse;
    }

    #hiddencell {
      padding: 0;
      margin: 0;
      border: 0;
      width: 100%;
    }

    #hiddencell > p {
      margin-bottom: 1px;
      background-color: {% settings_value "BACKGROUND_COLOUR" %}80;
      padding-left: 12px;
    }

    #hiddencell > p.streamed {
      background-color: {% settings_value "STREAMED_COLOUR" %}80;
    }

    #ticked {
      background-color: {% settings_value "BACKGROUND_COLOUR" %};
    }

    #ticked-stream-only {
      background-color: {% settings_value "STREAMED_COLOUR" %};
    }
  </style>
{% endblock %}

{% block nav-table %}
  <li class="nav-item active">
    <a class="nav-link" href="#">Table<span class="sr-only">(current)</span></a>
  </li>
{% endblock %}

{% block content %}
  <div class='row'>
    <div class='col-md-11'>
    {% if filter %}
      {% crispy filter.form %}
      {% comment %} <form action="" method="get" class="form form-inline">
          {% bootstrap_form filter.form layout='inline' bound_css_class='' %}
          {% bootstrap_field filter.form.duration_range %}
          {% bootstrap_button 'filter' %}
      </form> {% endcomment %}
    {% endif %}
    </div>
    <div class='col-md-1 text-right'>
      <div class='row'>
        {% if random_uri %}
        <span>Play random</span>
        <a class="spotify_play" href="/play/{{work_id}}/">
          <img uri="{{random_uri}}:play" src="/static/images/Spotify-Shuffle-Button.png" width="32px;">
        </a>
        {% endif %}
      </div>
      <div class='row'>
        <a class="expand_all">
          <i class="fa-regular fa-square-plus fa-lg"></i>
        </a>
        <a class="collapse_all">
          <i class="fa-regular fa-square-minus fa-lg"></i>
        </a>
      </div>
    </div>
  </div>
  <script src="{% static 'js/custom_slider.js' %}"></script>

  {% render_table table %}
{% endblock %}

melodramatick/work/templates/work/table.html
{% extends 'django_tables2/bootstrap4.html' %}
{% load django_tables2 %}
{% load i18n %}

{% block table.thead %}
    {% if table.show_header %}
        <thead {{ table.attrs.thead.as_html }}>
        <tr>
        {% for column in table.columns %}
            {% if column.name != "performance_list" %}
                <th {{ column.attrs.th.as_html }}>
                    {% if column.orderable %}
                        <a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header }}</a>
                    {% else %}
                        {{ column.header }}
                    {% endif %}
                </th>
            {% endif %}
        {% endfor %}
        </tr>
        </thead>
    {% endif %}
{% endblock table.thead %}

{% block table.tbody.row %}
    <tr {{ row.attrs.as_html }}>
        {% for column, cell in row.items %}
            {% if column.name != "performance_list" %}
                <td {{ column.attrs.td.as_html }}>{% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}</td>
            {% endif %}
        {% endfor %}
    </tr>
    <tr>
        {% for column, cell in row.items %}
            {% if column.name == "performance_list" %}
                <td id="hiddencell" colspan="8">{{ cell|linebreaks }}</td>
            {% endif %}
        {% endfor %}
    </tr>
{% endblock table.tbody.row %}

melodramatick/work/templates/work/work_detail.html
{% extends 'base.html' %}
{% load settings %}
{% load mathfilters %}

{% block title %}{{ object.title }} ({{ object.year }}){% endblock %}

{% block content %}
  <div class="d-flex">
    <div>
      <h1>{{ object.composer.surname }} - {{ object.title }} ({{ object.year }})</h1>
    </div>
    {% if user.is_superuser %}
    <div class="ml-auto">
      {% block edit_button %}
      {% comment %} <a href="{% url 'admin:table_opera_change' object.id %}">Edit</a> {% endcomment %}
      {% endblock %}
    </div>
    {% endif %}
  </div>
  <div class="row" {% if ticked %} style="background-color: {% settings_value 'BACKGROUND_COLOUR' %}80;" {% endif %}>
    <div class="col-sm-5">
      <h3>Information</h3>
      <dl class="row">
        <dt class="col-sm-3">Year</dt>
        <dd class="col-sm-9">{{ object.year }}</dd>
        <dt class="col-sm-3">Composer</dt>
        <dd class="col-sm-9">{{ object.composer.full_name }}</dd>
        {% if object.sub_genre %}
        <dt class="col-sm-3">Sub-Genre</dt>
        <dd class="col-sm-9">{{ object.sub_genre }}</dd>
        {% endif %}
        <dt class="col-sm-3">Era</dt>
        <dd class="col-sm-9">{{ object.era }}</dd>
        {% block information_rows %}
        {% comment %} <dt class="col-sm-3">Language</dt>
        <dd class="col-sm-9">{{ object.language_verbose }}</dd> {% endcomment %}
        {% endblock %}
        {% if object.notes %}
        <dt class="col-sm-3">Notes</dt>
        <dd class="col-sm-9">
          <p>{{ object.notes }}</p>
        </dd>
        {% endif %}
        {% if object.aka.all %}
        <dt class="col-sm-3">AKA</dt>
        <dd class="col-sm-9">
          <p>{% for aka in object.aka.all %}"{{ aka }}"{% if not forloop.last %}, {% endif %}{% endfor %}</p>
        </dd>
        {% endif %}
      </dl>
      {% if object.album.all %}
      <div class="row">
        <div class="col-sm-9">
          <h3>Spotify playlists</h3>
          <ul class="list-group">
            {% for album in object.album.all %}
            <li class="list-group-item">
              <div class="content d-flex w-100 justify-content-between">
                <div>
                  <a class="spotify_link" href="{{ album.uri }}:play">
                    <img src="{{ album.image }}" width="120px;">
                  </a>
                </div>
                <div>
                  <p>Duration: {{ album.duration }} minutes</p>
                  <a class="spotify_play" href="/play/{{ object.id }}/">
                    <img uri="{{ album.uri }}:play" src="/static/images/Spotify-Play-Button.png" width="32px;">
                  </a>
                </div>
              </div>
            </li>
            {% endfor %}
          </ul>
          <div class="float-right">
            <h5>Total listens: {{ listen_count }}</h5>
          </div>
        </div>
      </div>
      {% endif %}
    </div>
    <div class="col-sm-6">
      <h3>In {{ object.top_lists }} top lists</h3>
      <ul class="list-group">
        {% for list_entry in object.list_item.all %}
        <li class="list-group-item">
          <div class="content d-flex w-100 justify-content-between">
            <a href="{% url 'work:index' %}?top_list={{ list_entry.list.id }}" class="mb-1">{{ list_entry.list }}</a>
            <span>{{ list_entry.position }}</span>
          </div>
          <div class="progress" style="opacity: 0.5;">
            {% widthratio list_entry.position|sub:1 list_entry.list.length 100 as width %}
            {% if list_entry.position == 1 %}
            <div class="progress-bar bg-success" role="progressbar" style="width: {{ 100|sub:width }}%" aria-valuenow="{{ 100|sub:width }}" aria-valuemin="0" aria-valuemax="100"></div>
            {% else %}
            <div class="progress-bar" role="progressbar" style="width: {{ 100|sub:width }}%" aria-valuenow="{{ 100|sub:width }}" aria-valuemin="0" aria-valuemax="100"></div>
            {% endif %}
          </div>
        </li>
        {% endfor %}
      </ul>
    </div>
    <div class="col-sm-1">
      <a href="{% url 'performance:tick' object.id %}">{{ tickbox }}</a>
    </div>
  </div>
{% endblock %}

melodramatick/work/templates/work/work_graphs.html
{% extends 'base.html' %}
{% load settings %}

{% block title %}Graphs{% endblock %}

{% block nav-graphs %}
  <li class="nav-item active">
    <a class="nav-link" href="#">Graphs<span class="sr-only">(current)</span></a>
  </li>
{% endblock %}

{% block content %}
  <div class="container-fluid py-3">
    <div class="flex-row">
      <div class="card-deck">
        <div class="card text-center">
          <div class="card-body align-bottom">
            {% settings_value "WORK_PLURAL_LABEL" as label %}
            <p class="card-title">{{ label|title }} in database:</p>
            <h2 class="card-text">{{ work_count }}</h2>
          </div>
        </div>
        <div class="card text-center">
          <div class="card-body align-bottom">
            <p class="card-title">Total user performances (excl. streams):</p>
            <h2 class="card-text">{{ user_performance_count }}</h2>
          </div>
        </div>
        <div class="card text-center">
          <div class="card-body align-bottom">
            <p class="card-title">Total user listens:</p>
            <h2 class="card-text">{{ user_listen_count }}</h2>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <img class="img-fluid" src='data:image/png;base64,{{ top }}'>
      </div>
      <div class="row">
        <div class="col-4">
          <img class="img-fluid" src='data:image/png;base64,{{ middle_left }}'>
        </div>
        <div class="col-4">
          {% if middle_centre %}<img class="img-fluid" src='data:image/png;base64,{{ middle_centre }}'>{% endif %}
        </div>
        <div class="col-4">
          {% if middle_right %} <img class="img-fluid" src='data:image/png;base64,{{ middle_right }}'>{% endif %}
        </div>
      </div>
      <div class="row">
        <div class="col-4">
          <img class="img-fluid" src='data:image/png;base64,{{ bottom_left }}'>
        </div>
        <div class="col-4">
          {% if bottom_centre %}<img class="img-fluid" src='data:image/png;base64,{{ bottom_centre }}'>{% endif %}
        </div>
        <div class="col-4">
          {% if bottom_right %}<img class="img-fluid" src='data:image/png;base64,{{ bottom_right }}'>{% endif %}
        </div>
      </div>
      <div class="row">
        {% if duration_hist %}<img class="img-fluid" src='data:image/png;base64,{{ duration_hist }}'>{% endif %}
      </div>
      <div class="row">
        {% if top_lists_bar %}<img class="img-fluid" src='data:image/png;base64,{{ top_lists_bar }}'>{% endif %}
      </div>
    </div>
    {% block additional_graphs %}{% endblock %}
  </div>
{% endblock %}